version: '3.1'
services :
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
        -  ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: test

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

  redis:
      image: redis
      restart: always
      ports:
          - 6379:6379





