# Generated by Django 4.2.4 on 2023-10-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_setting_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='discounted_price',
        ),
    ]
